FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/London

# cd /usr/local/runme
WORKDIR /usr/local/runme

# define a password for webssh user
ARG SSH_PASS=wupassword

RUN apt-get update
RUN apt-get install -y openssh-server openssh-client net-tools nano
RUN useradd -m -s /bin/bash -p $(openssl passwd -1 $SSH_PASS) webssh
RUN usermod -g www-data webssh && usermod -a -G www-data,root root
	


